config/routes.rb
Rails.application.routes.draw do
  root 'users#login'


  resources :users 
  resources :investments
  resources :transactions
  resources :goals 

  #custom login and logout routes for users 
  # HTTPVERB "URL", to: "CONTROLLER_NAME#METHOD_NAME"
  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#handle_login"
  delete "/logout", to: "users#logout"


  get "/stocks_form", to: "investments#stocks_form", as: "stocks_form"
  get "/stocks", to: "investments#stocks", as: "stocks"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user

    validates :title, presence: true
    validates :amount, presence: true, numericality: {
        greater_than: 0,
    }
end


# Set method in model so we can calculate how long it would take to save up to this goal on the show page
    # def calculate_time
    # end

app/models/investment.rb
class Investment < ApplicationRecord
    has_many :transactions
    has_many :users, through: :transactions

#     def total_price(quantity)
#         total = 0
#         total += self.stock_quote.delayed_price * quantity
#         return total
#     end

#     # helper method
#     def update_balance
#         @user.transaction.balance = @user.transaction.balance - self.total_price
#     end

# private

#     def enough_funds
#         if @user.transaction.balance < self.total_price
#             flash[:invest_failure] << "You do not have enough funds to purchase this stock."
#         elsif @user.transaction.balance >= self.total_price
#             flash[:success] << "Purchase completed"
#             self.update_balance
#         end
#     end

end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :investments
    belongs_to :users

    # validations?
    
    def last_four_numbers
        prints "XXXXXX" + self.account_number
    end

    # need methods to update balance

end

app/models/user.rb
class User < ApplicationRecord
    has_many :goals
    has_many :transactions
    has_many :investments, through: :transactions

    validates :name, presence: true
    validates :email_address, presence: true
    validates :email_address, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :password, presence: true, length: {
        minimum: 7
    }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized

    # Allows you to use this method in the views
    helper_method :logged_in?
    

    def set_current_user
        @current_user = User.find_by(id: session[:user])
    end

    def logged_in?
        !!set_current_user
    end

    def authorized
        redirect_to new_user_path unless logged_in?
    end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :find_goal, only: [:show, :edit, :update, :destroy]

    def index
        @user = @current_user
    end

    def show
        @goal = Goal.find(params[:id])
    end

    def new
        @goal = Goal.new
    end

    def create
        @user = @current_user
        @goal = Goal.create(title: goals_params[:title], amount: goals_params[:amount], user_id: @user.id)
        
        if @goal.valid?
            @goal.save
            flash[:success] = "You've created one new goal!"
            redirect_to goals_path
        else
            flash[:my_errors] = @goal.errors.full_messages
            redirect_to new_goal_path
        end
    end

    def edit
    end

    def update
        @goal.update(goals_params)
        redirect_to goal_path(@goal)
    end

    def destroy
        @goal.destroy
        redirect_to goals_path
    end

private

    def find_goal
        @goal = Goal.find(params[:id])
    end

    def goals_params
        params.require(:goal).permit!
    end

end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
    skip_before_action :authorized, only: [:index, :show, :stocks, :stocks_form]

    def index
        @investments = Investment.all
        @ticker = ""
    end

    def show
    end
    
    def new 
        @investment = Investment.new
        @stock_quote = params[:stock]
    end  

    def create 
        price = investment_params[:price].to_f
        if (price < @current_user.balance)
            @investment = Investment.create(investment_params)
            session[:investment] = @investment.id
            redirect_to investments_path
        else
            flash[:my_errors] = ["We're sorry you do not have enough funds to purchase this stock"]
            redirect_to stocks_form_path
        end 
    end 

    def stocks
        begin
            client = IEX::Api::Client.new(
                publishable_token: 'pk_1f8c94d01b95418487f25d4f8b609c9e',
                endpoint: 'https://cloud.iexapis.com/v1')
            
            @stock_quote = client.quote(params[:ticker])
        rescue Exception => e
            # TODO add error handling and flash
        end
    end 

    private 

    def investment_params
        params.require(:investment).permit!
    end

    
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    def index
        @transactions = Transaction.all 
    end 

    def show
        @transaction = Transaction.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create, :login, :handle_login]

    def new
        @user = User.new
    end

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user] = @user.id
            redirect_to users_path
        else
            redirect_to new_user_path
        end
    end 


    def login
    end

    def handle_login
        @user = User.find_by(name: params[:name])
        if @user && @user.authenticate(params[:password])
            session[:user] = @user.id
            redirect_to users_path
        else 
            flash[:my_errors] = "Incorrect Username or password. Please try again."
            redirect_to login_path
        end 
    end

    def logout
        session[:user] == nil
        redirect_to login_path
    end

private

    def user_params
        params.require(:user).permit(:name, :email_address, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/edit.html.erb
<h2 class="goals-edit-header">Editing Goal</h2>

<div class="container"> 
    <div class="row ">
        <div class="col-lg-7 mx-auto">
            <div class="card mt-2 mx-auto p-4 bg-light">
                <div class="card-body bg-light">
                    <div class="container">
                        <%= form_for @goal do |f| %>
                                <div class="row">
                                    <div class="col-md-6">
                                        <%= f.label :title%>
                                        <%= f.text_field :title %>
                                        </div>
                                    </div>
                            <br>
                            <br>
                            <br>
                            <%= f.label :amount %>
                            <%= f.number_field :amount %>
                            <br>
                            <br>
                            <br>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-12"> <input type="submit" class="btn btn-primary btn-send pt-2 btn-block " value="Update goal"> </div>
                            </div>
                        <% end %>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/goals/index.html.erb
<div class="goals-index">Your Personal Financial Goals are: </div>

<div class="goal-list">
    <% @user.goals.each do |goal| %>
        <p class="goal-list-box">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-hexagon-half" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M14 4.577L8 1v14l6-3.577V4.577zM8.5.134a1 1 0 0 0-1 0l-6 3.577a1 1 0 0 0-.5.866v6.846a1 1 0 0 0 .5.866l6 3.577a1 1 0 0 0 1 0l6-3.577a1 1 0 0 0 .5-.866V4.577a1 1 0 0 0-.5-.866L8.5.134z"/>
            </svg>
        <%= link_to goal.title, goal_path(goal.id) %>
        </p>
    <% end %>
    </ul>
</div>

<br>
<br>
<br>
<br>
<br>

<div class="goals-what-to-do">
    <p class="goals-index-links-a">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
        </svg>
    <%= link_to "Home", users_path %></p>
    <br>
    <p class="goals-index-links-b">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
        </svg>
    <%= link_to "Create a new goal", new_goal_path %></p>
    <br>
    <p class="goals-index-links-c">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
        </svg>
    <%= link_to "View My Investments", investments_path %></p>
</div>

app/views/goals/new.html.erb
<h2 class="goals-new-header">Create a new goal for yourself</h2>



<div class="container"> 
    <div class="row ">
        <div class="col-lg-7 mx-auto">
            <div class="card mt-2 mx-auto p-4 bg-light">
                <div class="card-body bg-light">
                        <div class="flash-errors-goals-new">
                        <% if flash[:my_errors] %>
                            <% flash[:my_errors].each do |message| %>
                            <p><%= message %></p>
                            <% end %>
                        <% end %>
                        </div>
                    <div class="container">
                        <%= form_for @goal do |f| %>
                                <div class="row">
                                    <div class="col-md-6">
                                        <%= f.label :title%>
                                        <%= f.text_field :title %>
                                        </div>
                                    </div>
                            <br>
                            <br>
                            <br>
                            <%= f.label :amount %>
                            <%= f.number_field :amount %>
                            <br>
                            <br>
                            <br>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-12"> <input type="submit" class="btn btn-primary btn-send pt-2 btn-block " value="Create new goal"> </div>
                            </div>
                        <% end %>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/goals/show.html.erb
<div class="goals-show-header">
    <h2>Goal: <%= @goal.title %></h2>
    <br>
    <h3>Amount: $<%= @goal.amount %></h3>
</div>
<br>
<br>
<br>


<div class="goals-show-choices">
    <p class="goals-show-choices-a">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-sliders" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"/>
        </svg>
        <%= link_to "Update Goal", edit_goal_path(@goal) %>
    </p>
    <br>
    <p class="goals-show-choices-b">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>   
        <%= link_to "Delete Goal", goal_path, method: :delete %>
    </p>
    <br>
    <p class="goals-show-choices-c">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-window" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M14 2H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1zM2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2z"/>
            <path fill-rule="evenodd" d="M15 6H1V5h14v1z"/>
            <path d="M3 3.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm1.5 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm1.5 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
        </svg>
        <%= link_to "View My Goals", goals_path%>
    </p>
</div>

app/views/investments/index.html.erb
<div class="font-invest-index-a">
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
    <%= link_to "Home", users_path %>
    <%= link_to "Find Stocks", stocks_form_path %>
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
        </svg>
</div>


<div class="investments-index-header">
    <h2 style="text-align:center;">Investments</h2>
</div>

<br>

<div class = 'my-investments'>
    <h3 style="text-align:center; "> <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-credit-card" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v1h14V4a1 1 0 0 0-1-1H2zm13 4H1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V7z"/>
  <path d="M2 10a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-1z"/>
</svg> Stock Ticker: ULTA</h3>
    <h4 style="text-align:center;">Ulta</h4>
    <div>
    <p style="text-align:center;">Number of Shares You Hold: 1</p>
    <p style="text-align:center;">Date Purchased: 09/28/2020 </p>
    <p style="text-align:center;">Purchased for: $224.82 </p>
    </div>
</div>

<br>

<div class = 'my-investments'>
    <h3 style="text-align:center;"> <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-credit-card" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v1h14V4a1 1 0 0 0-1-1H2zm13 4H1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V7z"/>
  <path d="M2 10a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-1z"/>
</svg> Stock Ticker: PFE</h3>
    <h4 style="text-align:center;">Pfizer</h4>
    <div>
    <p style="text-align:center;">Number of Shares You Hold: 3</p>
    <p style="text-align:center;">Date Purchased: 09/30/2020</p>
    <p style="text-align:center;">Purchased for: $38.32</p>
    </div>
</div>

<br>

<div class = 'my-investments'>
    <h3 style="text-align:center;"> <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-credit-card" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v1h14V4a1 1 0 0 0-1-1H2zm13 4H1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V7z"/>
  <path d="M2 10a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-1z"/>
</svg> Stock Ticker: LMT</h3>
    <h4 style="text-align:center;">Lockheed Martin</h4>
    <div>
    <p style="text-align:center;">Number of Shares You Hold: 1</p>
    <p style="text-align:center;">Date Purchased: 10/01/2020 </p>
    <p style="text-align:center;">Purchased for: $382.13</p>
    </div>
</div>

app/views/investments/new.html.erb
<body>

<div>
<%= link_to "View My Investments", investments_path %>
</div>
<br>
<div><%= link_to "Find Stocks", stocks_form_path %></div>

<div>
    <h2>Purchase Stock</h2>
    <br>
</div>

    <%# if self.enough_funds? %>
        <%#= self.enough_funds %>

<div>
    <% if @stock_quote %>
        <p>Stock Company Name: <%= @stock_quote['company_name'] %></p>
        <p>Stock Symbol: <%= @stock_quote['symbol'] %> </p>
        <p>Current Price: $<%= @stock_quote['iex_realtime_price'] %></p>
        <br>
        <%= form_for(@investment) do |f|  %>
            <%= f.hidden_field  :name, :value => @stock_quote['company_name'] %>
            <%= f.hidden_field  :price, :value => @stock_quote['iex_realtime_price'] %>
            <%= f.submit "CONFIRM" %>
        <% end %>
    <% end %>
</div>

</body>

app/views/investments/stocks.html.erb
<div class="my-transactions-balance">
    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
        <%= link_to "Back", stocks_form_path%>
</div>

<h1 class="stock-info-header">
    Show Stock Info
</h1>
<br>
<br>

<div class = "stock-prices">
    <% if @stock_quote %>
    <h3><%= @stock_quote.company_name %></h3>
    <p>Symbol: <%= @stock_quote.symbol %> </p>
    <p>Price: $<%= @stock_quote.iex_realtime_price %> </p>
    <p>52 Week Low: $<%= @stock_quote.week_52_low %> </p>
    <p>52 Week High: $<%= @stock_quote.week_52_high %> </p>
    <p>Market Cap: <%= @stock_quote.market_cap %> </p>
    <p>Volume: <%= @stock_quote.avg_total_volume %> </p>
    <% else  %>
    <h3> We're sorry but the company symbol you've entered is invalid. </h3>
    <% end  %>
</div>
<br>

<p class="purchase-stock-choice">
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-shop" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z"/>
    </svg>
<%= link_to "Purchase Stock?", {:controller => "investments", :action => "new", :stock => @stock_quote } %>
</p>

app/views/investments/stocks_form.html.erb
<div class="my-investments-arrow">
<svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
<%= link_to "My Investments", investments_path%>
</div>

<h1 class="my-investments-header">
    Look Up Stock Information
    </h1>
    <% if flash[:my_errors] %>
        <% flash[:my_errors].each do |error| %>
        <p style = "color:red;"><%= error %></p> 
        <% end  %>
<% end  %>

<div class="stock-lookup-ticker">
    <%= form_tag stocks_path, method: 'get' do |f|  %>
    <%= label_tag :ticker %>
    <%= text_field_tag :ticker %>
    <%= submit_tag "SUBMIT" %>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Khan-Liang</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancialApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>

    <% if logged_in? %>
        <%#= render 'layouts/navbar' %>
        <%# Logged in as  <%#= @current_user.name %>
      <% end %>

    </nav>
    <div class = "background border-black"> 
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h2 class="welcome-users-index">Welcome, <%= @current_user.name %></h2>

<h3 class="what-do-today"> What would you like to do today? </h3>

    <div class="users-index-menu"> 
        <br>
            <p class="users-index-choice-a">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
                </svg>    
            <%= link_to "View My Financial Goals", goals_path%>
            </p>

            <p class="users-index-choice-b">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
                </svg>
            <%= link_to "Check My Bank Balance", transactions_path %>
            </p>

            <p class="users-index-choice-c">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
                </svg>
            <%= link_to "View My Investments", investments_path%>
            </p>
        <div class="log-out-button">  
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-compact-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M6.776 1.553a.5.5 0 0 1 .671.223l3 6a.5.5 0 0 1 0 .448l-3 6a.5.5 0 1 1-.894-.448L9.44 8 6.553 2.224a.5.5 0 0 1 .223-.671z"/>
                </svg>
            <%#= button_to "Log Out", logout_path, method: :delete%>
            <%= link_to "Log Out", logout_path, method: :delete%>
        </div>

    </div>